### ISSUE TITLE
Warning in CI

### ISSUE THREAD

**Issue by ClaudiaRaffaelli** [FrancescoScandiffio/shop-totem#37]
In [maven_ubunty.yml](https://github.com/FrancescoScandiffio/shop-totem/blob/ee9a08bcc766cf97c97a813dc1fb837c57bcf8de/.github/workflows/maven_ubuntu.yml) if the step executing unit tests fails is automatically executed another step for saving the screenshots of failed tests. However if no UI test has failed there is no content in the `failed-gui-tests` folder of screenshots. 
This results in the following warning:
`Warning: No files were found with the provided path: **/failed-gui-tests. No artifacts will be uploaded.`

**Comment by FrancescoScandiffio** [comment]
So far I have not found a github action with which to check if a folder is empty but i think we can do it with command line statements. The workflow i have in mind is something like this:

<ol>
<li>New step: check if folder `failed-gui-tests` exists and is empty </li>
<ol>
<li> Find the full path of folder `failed-gui-tests`</li>
<li> Use the full path to check if the folder is empty. </li>
<li> Write the script result as an output parameter of the step</li>
</ol>
<li>Use the output parameter of the new step to skip or save the failed-gui-tests directory</li></ol>

- See the [Actions documentation](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) on how to set a workflow variable from a bash script.
- On ubuntu we can find the full path of a directory and quit when the first match occurs with:
  `find . 2>/dev/null -name dirName -type d -print -quit`

**Comment by ClaudiaRaffaelli** [comment]
It seems like a good idea, but since the same problem could occur on Windows and MacOS workflows we could simply suppress the warning. The `if-no-files-found` option might suit our requirements ([see documentation](https://github.com/actions/upload-artifact#customization-if-no-files-are-found)).
In our case:
```yml
- name: Archive Screenshots
  uses: actions/upload-artifact@v2
  if: ${{ always() && (steps.mvnTest.outcome == 'failure') }}
  with:
    name: screenshots
    path: '**/failed-gui-tests/'
    if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
```
